# .github/workflows/main.yml
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-app

    - name: Run unit tests
      run: docker run my-app python -m pytest test_app.py

    - name: Run integration tests
      run: docker run my-app python -m unittest test_endtoend_app.py

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push to DockerHub
      run: docker tag my-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest && docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest